export const USER_NUEVO = 'USER_NUEVO'
export const USER_NUEVO_EXITOSO = 'USER_NUEVO_EXITOSO'
export const USER_NUEVO_ERROR = 'USER_NUEVO_ERROR'

export const USER_CARGAR = 'USER_NUEVO'
export const USER_CARGAR_EXITOSO = 'USER_NUEVO'
export const USER_CARGAR_ERROR = 'USER_NUEVO'

export const GET_ONE_USER_EDITAR = 'GET_ONE_USER_EDITAR'
export const GET_ONE_USER_EDITAR_EXITO = 'GET_ONE_USER_EDITAR_EXITO'
export const GET_ONE_USER_EDITAR_ERROR = 'GET_ONE_USER_EDITAR_ERROR'


export const GET_ONE_USER_ELIMINAR = 'GET_ONE_USER_ELIMINAR'
