version: '3'
services: 
    front:
        container_name: front
        build: .
        ports: 
            - 3000:3000
        restart: always
        networks: 
            - net2
networks: 
    net2: